services:
  astro:
    image: astro:${TAG_ASTRO_VERSION:-latest}
    build:
      context: .
      args:
        PUBLIC_API_URL: ${PUBLIC_API_URL}
    environment:
      NODE_ENV: ${NODE_ENV}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    ports:
      - "${ASTRO_PORT:-4321}:4321"
    restart: unless-stopped