services:
  astro:
    image: astro:${TAG_ASTRO_VERSION:-latest}
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "${ASTRO_PORT:-4321}:4321"
    restart: unless-stopped