services:

  db:
    image: postgres:${TAG_DB_VERSION:-latest}
    build: ./db/
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    image: express:${TAG_EXPRESS_VERSION:-latest}
    build: .
    volumes:
      - ./:/server 
    ports:
      - "${EXPRESS_PORT:-3000}:3000"
    command: sh -c "npm run migration:run:prod && npm start"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SALT_ROUNDS: ${SALT_ROUNDS}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
    depends_on:
      - db
    restart: unless-stopped
volumes:
  postgres_data: